name: VirtualEdit
version: '${project.version}'
main: ca.encodeous.virtualedit.Plugin
api-version: 1.13
depend: [ ProtocolLib ]
authors: [ Encodeous ]
description: Fast client-side world editing library
